-- Extends the check_form_items catalog (introduced in 0039) to also cover:
--  - CHECK_TO_LINE: the pilot Check to Line Preparation assessment items,
--    previously hardcoded per-fleet in backend/db/phase4-items.js (shared
--    with the Phase 4 form, which keeps its own copy - only the Check to
--    Line side is being made admin-editable here, per the operator's
--    request, and only for pilots - the cabin attendant Check to Line items
--    stay as a fixed 6-item list in CtlForm.jsx). fleet distinguishes the
--    three per-fleet item sets (items vary slightly per fleet); section
--    holds the category (Preflight, Procedures, etc, same grouping as
--    Phase 4); notes holds the free-form clarifying note a few items have.
--  - GROUND_INSTRUCTOR_COMPETENCY: the SA_520 Flight Standards Personnel
--    (Ground) Competency Check, a recurring (12-month) check on staff
--    eligible to check/train Emergency Procedures. All 11 items are plain
--    Yes/No, no sections.
ALTER TABLE check_form_items ADD COLUMN fleet fleet;
ALTER TABLE check_form_items ADD COLUMN notes TEXT;

-- Check to Line - Dash 8 (SA_503 Phase 4 item set)
INSERT INTO check_form_items (form_key, fleet, section, kind, description, notes, sort_order) VALUES
  ('CHECK_TO_LINE', 'DASH_8', 'Preflight', 'tick', 'Pre-flight/Daily Inspection (As per AMM)', NULL, 0),
  ('CHECK_TO_LINE', 'DASH_8', 'Preflight', 'tick', 'Cockpit setup', NULL, 1),
  ('CHECK_TO_LINE', 'DASH_8', 'Preflight', 'tick', 'Flight Planning', 'Not required for First Officer', 2),
  ('CHECK_TO_LINE', 'DASH_8', 'Preflight', 'tick', 'Crew Coordination/Briefing', NULL, 3),
  ('CHECK_TO_LINE', 'DASH_8', 'Preflight', 'tick', 'Passenger supervision/public relations', NULL, 4),
  ('CHECK_TO_LINE', 'DASH_8', 'Performance Calculations', 'tick', 'Take off limits', NULL, 5),
  ('CHECK_TO_LINE', 'DASH_8', 'Performance Calculations', 'tick', 'Landing Limits', NULL, 6),
  ('CHECK_TO_LINE', 'DASH_8', 'Performance Calculations', 'tick', 'Emergency re-calculations', 'e.g. Flapless landing, antiskid failure, etc.', 7),
  ('CHECK_TO_LINE', 'DASH_8', 'Weight and Balance', 'tick', 'Complete & Accurate', NULL, 8),
  ('CHECK_TO_LINE', 'DASH_8', 'Procedures', 'tick', 'Scans', NULL, 9),
  ('CHECK_TO_LINE', 'DASH_8', 'Procedures', 'tick', 'Checklist Use', NULL, 10),
  ('CHECK_TO_LINE', 'DASH_8', 'Procedures', 'tick', 'Standard Operating Procedures', NULL, 11),
  ('CHECK_TO_LINE', 'DASH_8', 'Procedures', 'tick', 'Radio Communication', NULL, 12),
  ('CHECK_TO_LINE', 'DASH_8', 'Procedures', 'tick', 'Knowledge of Company Manuals', NULL, 13),
  ('CHECK_TO_LINE', 'DASH_8', 'Procedures', 'tick', 'Clear and concise briefings', NULL, 14),
  ('CHECK_TO_LINE', 'DASH_8', 'Route Knowledge', 'tick', 'Appropriate use of GNSS and enroute Navigation aids', NULL, 15),
  ('CHECK_TO_LINE', 'DASH_8', 'Route Knowledge', 'tick', 'Knowledge of communication and air traffic services provided', NULL, 16),
  ('CHECK_TO_LINE', 'DASH_8', 'General Aircraft Handling', 'tick', 'Flying accurate and smooth, in line with SOPs and Jeppesen', NULL, 17),
  ('CHECK_TO_LINE', 'DASH_8', 'General Aircraft Handling', 'tick', 'Aircraft systems used correctly', NULL, 18),
  ('CHECK_TO_LINE', 'DASH_8', 'Aircraft System Knowledge', 'tick', 'System: GNSS operation', NULL, 19),
  ('CHECK_TO_LINE', 'DASH_8', 'Emergency Procedures', 'tick', 'Emergency procedure 1 assessed', 'Note which emergency in Remarks', 20),
  ('CHECK_TO_LINE', 'DASH_8', 'Emergency Procedures', 'tick', 'Emergency procedure 2 assessed', 'Note which emergency in Remarks', 21),
  ('CHECK_TO_LINE', 'DASH_8', 'Emergency Procedures', 'tick', 'Emergency procedure 3 assessed', 'Note which emergency in Remarks', 22),
  ('CHECK_TO_LINE', 'DASH_8', 'Instrument Approach 1', 'tick', 'Tracking', NULL, 23),
  ('CHECK_TO_LINE', 'DASH_8', 'Instrument Approach 1', 'tick', 'Instrument flying smooth and accurate', NULL, 24),
  ('CHECK_TO_LINE', 'DASH_8', 'Instrument Approach 1', 'tick', 'Configuration', NULL, 25),
  ('CHECK_TO_LINE', 'DASH_8', 'Instrument Approach 1', 'tick', 'Speed control', NULL, 26),
  ('CHECK_TO_LINE', 'DASH_8', 'Instrument Approach 1', 'tick', 'Vertical profile', NULL, 27),
  ('CHECK_TO_LINE', 'DASH_8', 'Instrument Approach 1', 'tick', 'Crew Coordination and Standard Calls', NULL, 28),
  ('CHECK_TO_LINE', 'DASH_8', 'Instrument Approach 2', 'tick', 'Tracking', NULL, 29),
  ('CHECK_TO_LINE', 'DASH_8', 'Instrument Approach 2', 'tick', 'Instrument flying smooth and accurate', NULL, 30),
  ('CHECK_TO_LINE', 'DASH_8', 'Instrument Approach 2', 'tick', 'Configuration', NULL, 31),
  ('CHECK_TO_LINE', 'DASH_8', 'Instrument Approach 2', 'tick', 'Speed control', NULL, 32),
  ('CHECK_TO_LINE', 'DASH_8', 'Instrument Approach 2', 'tick', 'Vertical profile', NULL, 33),
  ('CHECK_TO_LINE', 'DASH_8', 'Instrument Approach 2', 'tick', 'Crew Coordination and Standard Calls', NULL, 34),
  ('CHECK_TO_LINE', 'DASH_8', 'Maintenance Procedures', 'tick', 'Defect recording - knowledge of procedure', NULL, 35),
  ('CHECK_TO_LINE', 'DASH_8', 'Maintenance Procedures', 'tick', 'Knowledge of MEL Application', NULL, 36),
  ('CHECK_TO_LINE', 'DASH_8', 'Post Flight Duties', 'tick', 'Actioned with due care', NULL, 37),
  ('CHECK_TO_LINE', 'DASH_8', 'Post Flight Duties', 'tick', 'Coordination with Terminal staff and Engineering', NULL, 38);

-- Check to Line - Metro 23 (SA_511 Phase 4 item set - identical structure to Dash 8)
INSERT INTO check_form_items (form_key, fleet, section, kind, description, notes, sort_order) VALUES
  ('CHECK_TO_LINE', 'METRO_23', 'Preflight', 'tick', 'Pre-flight/Daily Inspection (As per 2B3)', NULL, 0),
  ('CHECK_TO_LINE', 'METRO_23', 'Preflight', 'tick', 'Cockpit setup', NULL, 1),
  ('CHECK_TO_LINE', 'METRO_23', 'Preflight', 'tick', 'Flight Planning', 'Not required for First Officer', 2),
  ('CHECK_TO_LINE', 'METRO_23', 'Preflight', 'tick', 'Crew Coordination/Briefing', NULL, 3),
  ('CHECK_TO_LINE', 'METRO_23', 'Preflight', 'tick', 'Passenger supervision/public relations', NULL, 4),
  ('CHECK_TO_LINE', 'METRO_23', 'Performance Calculations', 'tick', 'Take off limits', NULL, 5),
  ('CHECK_TO_LINE', 'METRO_23', 'Performance Calculations', 'tick', 'Landing Limits', NULL, 6),
  ('CHECK_TO_LINE', 'METRO_23', 'Performance Calculations', 'tick', 'Emergency re-calculations', 'e.g. Flapless landing, antiskid failure, etc.', 7),
  ('CHECK_TO_LINE', 'METRO_23', 'Weight and Balance', 'tick', 'Complete & Accurate', NULL, 8),
  ('CHECK_TO_LINE', 'METRO_23', 'Procedures', 'tick', 'Scans', NULL, 9),
  ('CHECK_TO_LINE', 'METRO_23', 'Procedures', 'tick', 'Checklist Use', NULL, 10),
  ('CHECK_TO_LINE', 'METRO_23', 'Procedures', 'tick', 'Standard Operating Procedures', NULL, 11),
  ('CHECK_TO_LINE', 'METRO_23', 'Procedures', 'tick', 'Radio Communication', NULL, 12),
  ('CHECK_TO_LINE', 'METRO_23', 'Procedures', 'tick', 'Knowledge of Company Manuals', NULL, 13),
  ('CHECK_TO_LINE', 'METRO_23', 'Procedures', 'tick', 'Clear and concise briefings', NULL, 14),
  ('CHECK_TO_LINE', 'METRO_23', 'Route Knowledge', 'tick', 'Appropriate use of GNSS and enroute Navigation aids', NULL, 15),
  ('CHECK_TO_LINE', 'METRO_23', 'Route Knowledge', 'tick', 'Knowledge of communication and air traffic services provided', NULL, 16),
  ('CHECK_TO_LINE', 'METRO_23', 'General Aircraft Handling', 'tick', 'Flying accurate and smooth, in line with SOPs and Jeppesen', NULL, 17),
  ('CHECK_TO_LINE', 'METRO_23', 'General Aircraft Handling', 'tick', 'Aircraft systems used correctly', NULL, 18),
  ('CHECK_TO_LINE', 'METRO_23', 'Aircraft System Knowledge', 'tick', 'System: GNSS operation', NULL, 19),
  ('CHECK_TO_LINE', 'METRO_23', 'Emergency Procedures', 'tick', 'Emergency procedure 1 assessed', 'Note which emergency in Remarks', 20),
  ('CHECK_TO_LINE', 'METRO_23', 'Emergency Procedures', 'tick', 'Emergency procedure 2 assessed', 'Note which emergency in Remarks', 21),
  ('CHECK_TO_LINE', 'METRO_23', 'Emergency Procedures', 'tick', 'Emergency procedure 3 assessed', 'Note which emergency in Remarks', 22),
  ('CHECK_TO_LINE', 'METRO_23', 'Instrument Approach 1', 'tick', 'Tracking', NULL, 23),
  ('CHECK_TO_LINE', 'METRO_23', 'Instrument Approach 1', 'tick', 'Instrument flying smooth and accurate', NULL, 24),
  ('CHECK_TO_LINE', 'METRO_23', 'Instrument Approach 1', 'tick', 'Configuration', NULL, 25),
  ('CHECK_TO_LINE', 'METRO_23', 'Instrument Approach 1', 'tick', 'Speed control', NULL, 26),
  ('CHECK_TO_LINE', 'METRO_23', 'Instrument Approach 1', 'tick', 'Vertical profile', NULL, 27),
  ('CHECK_TO_LINE', 'METRO_23', 'Instrument Approach 1', 'tick', 'Crew Coordination and Standard Calls', NULL, 28),
  ('CHECK_TO_LINE', 'METRO_23', 'Instrument Approach 2', 'tick', 'Tracking', NULL, 29),
  ('CHECK_TO_LINE', 'METRO_23', 'Instrument Approach 2', 'tick', 'Instrument flying smooth and accurate', NULL, 30),
  ('CHECK_TO_LINE', 'METRO_23', 'Instrument Approach 2', 'tick', 'Configuration', NULL, 31),
  ('CHECK_TO_LINE', 'METRO_23', 'Instrument Approach 2', 'tick', 'Speed control', NULL, 32),
  ('CHECK_TO_LINE', 'METRO_23', 'Instrument Approach 2', 'tick', 'Vertical profile', NULL, 33),
  ('CHECK_TO_LINE', 'METRO_23', 'Instrument Approach 2', 'tick', 'Crew Coordination and Standard Calls', NULL, 34),
  ('CHECK_TO_LINE', 'METRO_23', 'Maintenance Procedures', 'tick', 'Defect recording - knowledge of procedure', NULL, 35),
  ('CHECK_TO_LINE', 'METRO_23', 'Maintenance Procedures', 'tick', 'Knowledge of MEL Application', NULL, 36),
  ('CHECK_TO_LINE', 'METRO_23', 'Post Flight Duties', 'tick', 'Actioned with due care', NULL, 37),
  ('CHECK_TO_LINE', 'METRO_23', 'Post Flight Duties', 'tick', 'Coordination with Terminal staff and Engineering', NULL, 38);

-- Check to Line - Fokker 100 (SA_811 Phase 4 item set)
INSERT INTO check_form_items (form_key, fleet, section, kind, description, notes, sort_order) VALUES
  ('CHECK_TO_LINE', 'FOKKER_100', 'Preflight', 'tick', 'Pre-flight/Daily Inspection (As per AMM)', NULL, 0),
  ('CHECK_TO_LINE', 'FOKKER_100', 'Preflight', 'tick', 'Cockpit setup', NULL, 1),
  ('CHECK_TO_LINE', 'FOKKER_100', 'Preflight', 'tick', 'Flight Planning', NULL, 2),
  ('CHECK_TO_LINE', 'FOKKER_100', 'Preflight', 'tick', 'Crew Coordination / Briefing', NULL, 3),
  ('CHECK_TO_LINE', 'FOKKER_100', 'Preflight', 'tick', 'Passenger supervision / public relations', NULL, 4),
  ('CHECK_TO_LINE', 'FOKKER_100', 'Preflight', 'tick', 'License and Medical checked', NULL, 5),
  ('CHECK_TO_LINE', 'FOKKER_100', 'Preflight', 'tick', 'Flight and Duty times checked', NULL, 6),
  ('CHECK_TO_LINE', 'FOKKER_100', 'Preflight', 'tick', 'Correct company documentation procedures applied', NULL, 7),
  ('CHECK_TO_LINE', 'FOKKER_100', 'Preflight', 'tick', 'Obtained and understood correct operational information', NULL, 8),
  ('CHECK_TO_LINE', 'FOKKER_100', 'Preflight', 'tick', 'Publications amended and complete', NULL, 9),
  ('CHECK_TO_LINE', 'FOKKER_100', 'Preflight', 'tick', 'Duties of a pilot', NULL, 10),
  ('CHECK_TO_LINE', 'FOKKER_100', 'Preflight', 'tick', 'Aircraft fully serviceable for flight', NULL, 11),
  ('CHECK_TO_LINE', 'FOKKER_100', 'Preflight', 'tick', 'Flight instruments and navigation aids checked before take-off', NULL, 12),
  ('CHECK_TO_LINE', 'FOKKER_100', 'Performance Calculations', 'tick', 'Take off limits', NULL, 13),
  ('CHECK_TO_LINE', 'FOKKER_100', 'Performance Calculations', 'tick', 'Landing Limits', NULL, 14),
  ('CHECK_TO_LINE', 'FOKKER_100', 'Performance Calculations', 'tick', 'Emergency re-calculations', 'e.g. Flapless landing, antiskid failure, etc.', 15),
  ('CHECK_TO_LINE', 'FOKKER_100', 'Weight and Balance', 'tick', 'Complete & Accurate', NULL, 16),
  ('CHECK_TO_LINE', 'FOKKER_100', 'Procedures', 'tick', 'Scans', NULL, 17),
  ('CHECK_TO_LINE', 'FOKKER_100', 'Procedures', 'tick', 'Checklist Use', NULL, 18),
  ('CHECK_TO_LINE', 'FOKKER_100', 'Procedures', 'tick', 'Standard Operating Procedures', NULL, 19),
  ('CHECK_TO_LINE', 'FOKKER_100', 'Procedures', 'tick', 'Radio Communication', NULL, 20),
  ('CHECK_TO_LINE', 'FOKKER_100', 'Procedures', 'tick', 'Knowledge of Company Manuals', NULL, 21),
  ('CHECK_TO_LINE', 'FOKKER_100', 'Procedures', 'tick', 'Clear and concise briefings', NULL, 22),
  ('CHECK_TO_LINE', 'FOKKER_100', 'Procedures', 'tick', 'Correctly identified navigation aids', NULL, 23),
  ('CHECK_TO_LINE', 'FOKKER_100', 'Procedures', 'tick', 'Accepted Navigation procedures used', NULL, 24),
  ('CHECK_TO_LINE', 'FOKKER_100', 'Procedures', 'tick', 'Flight tolerance as per MOS part 61 schedule 8', NULL, 25),
  ('CHECK_TO_LINE', 'FOKKER_100', 'Procedures', 'tick', 'Turbulence penetration', 'Demonstrated or described', 26),
  ('CHECK_TO_LINE', 'FOKKER_100', 'Route Knowledge', 'tick', 'Appropriate use of FMS / GNSS and enroute Navigation aids', NULL, 27),
  ('CHECK_TO_LINE', 'FOKKER_100', 'Route Knowledge', 'tick', 'Knowledge of communication and air traffic services provided', NULL, 28),
  ('CHECK_TO_LINE', 'FOKKER_100', 'General Aircraft Handling', 'tick', 'Flying accurate and smooth, in line with SOPs and Jeppesen', NULL, 29),
  ('CHECK_TO_LINE', 'FOKKER_100', 'General Aircraft Handling', 'tick', 'Aircraft systems used correctly', NULL, 30),
  ('CHECK_TO_LINE', 'FOKKER_100', 'Aircraft System Knowledge', 'tick', 'System: FMS / GNSS operation', 'Refer Appendix 1', 31),
  ('CHECK_TO_LINE', 'FOKKER_100', 'Emergency Procedures', 'tick', 'Emergency procedure 1 assessed', 'Note which emergency in Remarks', 32),
  ('CHECK_TO_LINE', 'FOKKER_100', 'Emergency Procedures', 'tick', 'Emergency procedure 2 assessed', 'Note which emergency in Remarks', 33),
  ('CHECK_TO_LINE', 'FOKKER_100', 'Emergency Procedures', 'tick', 'Emergency procedure 3 assessed', 'Note which emergency in Remarks', 34),
  ('CHECK_TO_LINE', 'FOKKER_100', 'Instrument Approach 1', 'tick', 'Tracking', NULL, 35),
  ('CHECK_TO_LINE', 'FOKKER_100', 'Instrument Approach 1', 'tick', 'Instrument flying smooth and accurate', NULL, 36),
  ('CHECK_TO_LINE', 'FOKKER_100', 'Instrument Approach 1', 'tick', 'Configuration', NULL, 37),
  ('CHECK_TO_LINE', 'FOKKER_100', 'Instrument Approach 1', 'tick', 'Speed control', NULL, 38),
  ('CHECK_TO_LINE', 'FOKKER_100', 'Instrument Approach 1', 'tick', 'Vertical profile', NULL, 39),
  ('CHECK_TO_LINE', 'FOKKER_100', 'Instrument Approach 1', 'tick', 'Crew Coordination and Standard Calls', NULL, 40),
  ('CHECK_TO_LINE', 'FOKKER_100', 'Instrument Approach 2', 'tick', 'Tracking', NULL, 41),
  ('CHECK_TO_LINE', 'FOKKER_100', 'Instrument Approach 2', 'tick', 'Instrument flying smooth and accurate', NULL, 42),
  ('CHECK_TO_LINE', 'FOKKER_100', 'Instrument Approach 2', 'tick', 'Configuration', NULL, 43),
  ('CHECK_TO_LINE', 'FOKKER_100', 'Instrument Approach 2', 'tick', 'Speed control', NULL, 44),
  ('CHECK_TO_LINE', 'FOKKER_100', 'Instrument Approach 2', 'tick', 'Vertical profile', NULL, 45),
  ('CHECK_TO_LINE', 'FOKKER_100', 'Instrument Approach 2', 'tick', 'Crew Coordination and Standard Calls', NULL, 46),
  ('CHECK_TO_LINE', 'FOKKER_100', 'Maintenance Procedures', 'tick', 'Defect recording - knowledge of procedure', NULL, 47),
  ('CHECK_TO_LINE', 'FOKKER_100', 'Maintenance Procedures', 'tick', 'Knowledge of MEL Application', NULL, 48),
  ('CHECK_TO_LINE', 'FOKKER_100', 'Post Flight Duties', 'tick', 'Actioned with due care', NULL, 49),
  ('CHECK_TO_LINE', 'FOKKER_100', 'Post Flight Duties', 'tick', 'Coordination with Terminal staff and Engineering', NULL, 50);

-- Ground Instructor Competency Check (SA_520) - 11 plain Yes/No items, no
-- sections or fleet.
INSERT INTO check_form_items (form_key, kind, description, sort_order) VALUES
  ('GROUND_INSTRUCTOR_COMPETENCY', 'tick', 'Material presented conformed with the approved syllabus', 0),
  ('GROUND_INSTRUCTOR_COMPETENCY', 'tick', 'Aids specified by the syllabus available and used in a proficient manner', 1),
  ('GROUND_INSTRUCTOR_COMPETENCY', 'tick', 'Instructor displayed adequate knowledge of the subject, including theory and the principles of operation', 2),
  ('GROUND_INSTRUCTOR_COMPETENCY', 'tick', 'Instructor proficient in operating training equipment (if applicable)', 3),
  ('GROUND_INSTRUCTOR_COMPETENCY', 'tick', 'Instructor effective, instructional technique satisfactory', 4),
  ('GROUND_INSTRUCTOR_COMPETENCY', 'tick', 'Speaking style was clear and easily understood', 5),
  ('GROUND_INSTRUCTOR_COMPETENCY', 'tick', 'Encouraged and stimulated participation', 6),
  ('GROUND_INSTRUCTOR_COMPETENCY', 'tick', 'Satisfactory use of training manuals or course notes issued to the students', 7),
  ('GROUND_INSTRUCTOR_COMPETENCY', 'tick', 'Supervision and conduct of examinations satisfactory', 8),
  ('GROUND_INSTRUCTOR_COMPETENCY', 'tick', 'Allowed time for questions and clarifications', 9),
  ('GROUND_INSTRUCTOR_COMPETENCY', 'tick', 'Demonstrated accuracy with recordkeeping', 10);
