-- Metro Pilot Training Checklist (SA 634) - same structure/categories as
-- the existing Dash 8 ground school items (see GroundSchoolPanel.jsx's
-- extraFieldsForCategory, generalized in this same change to match any
-- "... (Module CBT)" category, not just Dash 8's), just for METRO_23.
INSERT INTO ground_school_items (fleet, category, description, notes, required) VALUES
  ('METRO_23', 'Admin', 'Ground School Course Setup', NULL, true),
  ('METRO_23', 'Admin', 'Induction Courses Completed', NULL, true),
  ('METRO_23', 'Admin', 'Operations Manuals Issued', NULL, true),
  ('METRO_23', 'Admin', 'QRH issued', NULL, true),
  ('METRO_23', 'Admin', 'Pilot training manual issued', NULL, true),
  ('METRO_23', 'Admin', 'Uniforms & PPE', NULL, true),
  ('METRO_23', 'Admin', 'Read and understood the last 6 months of Skippers Memos', NULL, true),

  ('METRO_23', 'Course', 'CAO 20.11 Theory', NULL, true),
  ('METRO_23', 'Course', 'CAO 20.11 Practical', NULL, true),
  ('METRO_23', 'Course', 'CAO 20.11 Wet Drill', NULL, true),
  ('METRO_23', 'Course', 'Maintenance Authority / Part 42 Exam', NULL, true),
  ('METRO_23', 'Course', 'First Aid', 'Metro pilots only - Medic One', true),
  ('METRO_23', 'Course', 'Human Factors & Non-Technical Skills', 'HFTS', true),
  ('METRO_23', 'Course', 'Dangerous Goods Awareness', 'Airsafe', true),

  ('METRO_23', 'Metro Ground School (Module CBT)', 'Aircraft General', NULL, true),
  ('METRO_23', 'Metro Ground School (Module CBT)', 'Electrical System', NULL, true),
  ('METRO_23', 'Metro Ground School (Module CBT)', 'Lighting & Master Warning Systems', NULL, true),
  ('METRO_23', 'Metro Ground School (Module CBT)', 'Fuel System', NULL, true),
  ('METRO_23', 'Metro Ground School (Module CBT)', 'Power Plant & Propellers', NULL, true),
  ('METRO_23', 'Metro Ground School (Module CBT)', 'Fire Protection', NULL, true),
  ('METRO_23', 'Metro Ground School (Module CBT)', 'Pneumatics', NULL, true),
  ('METRO_23', 'Metro Ground School (Module CBT)', 'Ice & Rain Protection', NULL, true),
  ('METRO_23', 'Metro Ground School (Module CBT)', 'Air Conditioning', NULL, true),
  ('METRO_23', 'Metro Ground School (Module CBT)', 'Pressurisation', NULL, true),
  ('METRO_23', 'Metro Ground School (Module CBT)', 'Hydraulics', NULL, true),
  ('METRO_23', 'Metro Ground School (Module CBT)', 'Landing Gear, Brakes & Nose Wheel Steering', NULL, true),
  ('METRO_23', 'Metro Ground School (Module CBT)', 'Flight Controls', NULL, true),
  ('METRO_23', 'Metro Ground School (Module CBT)', 'Avionics', NULL, true),
  ('METRO_23', 'Metro Ground School (Module CBT)', 'Oxygen', NULL, true),
  ('METRO_23', 'Metro Ground School (Module CBT)', 'EGPWS', NULL, true),
  ('METRO_23', 'Metro Ground School (Module CBT)', 'Weight & balance', NULL, true),
  ('METRO_23', 'Metro Ground School (Module CBT)', 'Performance', NULL, true),
  ('METRO_23', 'Metro Ground School (Module CBT)', 'Phase 1', '100% pass mark', true),
  ('METRO_23', 'Metro Ground School (Module CBT)', 'Limitations', '100% pass mark', true),
  ('METRO_23', 'Metro Ground School (Module CBT)', 'FO1 Knowledge Exam', 'May not be required if candidate is already a Skippers Employee or has already received training in its use', false),
  ('METRO_23', 'Metro Ground School (Module CBT)', 'Weather Radar', 'May not be required if candidate is already a Skippers Employee or has already received training in its use', false),
  ('METRO_23', 'Metro Ground School (Module CBT)', 'CFIT / ALAR', 'May not be required if candidate is already a Skippers Employee or has already received training in its use', false),
  ('METRO_23', 'Metro Ground School (Module CBT)', 'PBN', 'May not be required if candidate is already a Skippers Employee or has already received training in its use', false),

  ('METRO_23', 'Observation Flights', 'Observation Flight 1', 'Minimum 2 required', true),
  ('METRO_23', 'Observation Flights', 'Observation Flight 2', 'Minimum 2 required', true),

  ('METRO_23', 'Pre-Simulator Assessment', 'Complete cockpit setup', NULL, true),
  ('METRO_23', 'Pre-Simulator Assessment', 'Complete TOLD card', NULL, true),
  ('METRO_23', 'Pre-Simulator Assessment', 'Brief take-off, approach and landing', NULL, true),
  ('METRO_23', 'Pre-Simulator Assessment', 'Use checklist', NULL, true),
  ('METRO_23', 'Pre-Simulator Assessment', 'Engine start procedure', NULL, true),
  ('METRO_23', 'Pre-Simulator Assessment', 'Taxi procedure', NULL, true),
  ('METRO_23', 'Pre-Simulator Assessment', 'Line up and take-off procedure', NULL, true),
  ('METRO_23', 'Pre-Simulator Assessment', 'Climb, cruise and descent procedure', NULL, true),
  ('METRO_23', 'Pre-Simulator Assessment', 'Shutdown procedure', NULL, true),
  ('METRO_23', 'Pre-Simulator Assessment', 'FMS use', 'If applicable', false),
  ('METRO_23', 'Pre-Simulator Assessment', 'Emergency procedures/Phase ones', NULL, true);
